routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web']], function() {
    Route::resource('mensagem', 'MensagemController');
});

Route::get('mensagem/destroy/{id}' ,array(
    'as'=>'mensagem.destroy',
    'uses'=>'MensagemController@delete'));


Route::post('mensagem/destroy/{id}' ,array(
    'as'=>'mensagem.remove',
    'uses'=>'MensagemController@remove'));

Route::get('/criarpopups', 'ScriptController@getMensagem');
Route::get('/informarleitura', 'ScriptController@setMensagemLida');

//Route::get('/criarpopups', ['middleware' => 'cors' , 'uses'=> 'ScriptController@getMensagem']);
//Route::get('/criarpopups', array('middleware' => 'cors', 'uses' => 'ScriptController@getMensagem'));
//Route::get('/informarleitura', array('middleware' => 'cors', 'uses' => 'ScriptController@setMensagemLida'));

app/Mensagem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mensagem extends Model
{
    protected $table = 'mensagem';
    
    protected $fillable=['codigo', 'descricao', 'site', 'chave', 'user_id', 'usuarios_permitidos', 'permanente'];
    
    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/MensagemController.php
<?php

namespace App\Http\Controllers;

use App\Mensagem;
use App\UsuarioMensagem;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class MensagemController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $id = Auth::id();

        if (Auth::guest()) {
            return redirect()->guest('login');
        }

        $mensagens = Mensagem::where('user_id', $id)->get();
        return view('mensagem.index', ['mensagensusuario' => $mensagens]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('mensagem.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        try {

            if (Auth::guest()) {
                return redirect()->guest('login');
            }

            $id = Auth::id();
            $mensagem = $request->all();

            $chaveAnteriorSite = Mensagem::where([['site', '=', $request->site], ['user_id', '=', $id]])->first();

            if ($chaveAnteriorSite != null) {
                $mensagem['chave'] = $chaveAnteriorSite['chave'];
                $mensagem['codigo'] = $chaveAnteriorSite['codigo'];
            } else {
                $chaveAnterior = Mensagem::where('user_id', $id)->get();

                if (count($chaveAnterior) > 0)
                    $mensagem['codigo'] = $chaveAnterior[0]['codigo'];
                else
                    $mensagem['codigo'] = str_pad(rand(1, 999999999999), 12, '0', STR_PAD_LEFT);

                $mensagem['chave'] = str_pad(rand(1, 99999999999999999999), 20, '0', STR_PAD_LEFT);
            }

            if (isset($mensagem['permanente'])){
                $mensagem['permanente'] = $permanente = true;
            } else {
                $mensagem['permanente'] = $permanente = false;
            }

            $mensagem['user_id'] = $id;

            if (!empty($mensagem['key'])) {
                $mensagem = Mensagem::where('id', $mensagem['key'])->first();
                $mensagem->descricao = $request->descricao;
                $mensagem->site = $request->site;
                $mensagem->permanente = $permanente;
                $mensagem->usuarios_permitidos = $request->usuarios_permitidos;
                $mensagem->save();
            } else {
                Mensagem::create($mensagem);
            }
            return redirect('mensagem')->with('message', 'Mensagem criada com sucesso!');
        } catch (Exception $exc) {
            return back()->with('error', 'Não foi possível realizar a operação');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bar  $bar
     * @return \Illuminate\Http\Response
     */
    public function show(Mensagem $mensagem) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bar  $bar
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        if (Auth::guest()) {
            return redirect()->guest('login');
        }
        $mensagem = Mensagem::where('id', $id)->first();
        $mensagem = Mensagem::where('id', $id)->first();
        if (!$mensagem) {
            abort(404);
        }

        return view('mensagem.edit', ['dadosMensagem' => $mensagem]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bar  $bar
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        /*
          $this->validate($request, [
          'nome' => 'required',
          'descricao' => 'required',
          ]);
         */
        //$mensagem = Mensagem::where('id', $id)->first();
        //$mensagem->descricao = $request->descricao;
        //$mensagem->site = $request->site;
        //$mensagem->save();
        //return redirect('mensagem')->with('message', 'Mensagem editado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bar  $bar
     * @return \Illuminate\Http\Response
     */
    public function remove($id) {
        try {
            if (Auth::guest()) {
                return redirect()->guest('login');
            }
            
            UsuarioMensagem::where('mensagem_id', $id)->delete();
            Mensagem::where('id', $id)->delete();
            
             return redirect('mensagem')->with('message', 'Mensagem criada com sucesso!');
        } catch (Exception $exc) {
            echo $exc->getTraceAsString();
        }
    }

    public function delete($id) {
        if (Auth::guest()) {
            return redirect()->guest('login');
        }

        $mensagem = Mensagem::where('id', $id)->first();
        if (!$mensagem) {
            abort(404);
        }

        return view('mensagem.destroy', ['dadosMensagem' => $mensagem]);
    }

}

resources/views/mensagem/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>CADASTRO DAS MENSAGENS</strong></div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('mensagem.store') }}">
                        {{ csrf_field() }}
                        @if (\Session::has('success'))
                        <div class="alert alert-success">
                            <p>{{ \Session::get('success') }}</p>
                        </div><br />
                        @endif
                        <div class="form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
                            <label for="descricao" class="col-md-4 control-label">Mensagem</label>

                            <div class="col-md-6">
                                <textarea id="descricao"  class="form-control" name="descricao" value="{{ old('descricao') }}" required autofocus ></textarea>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('site') ? ' has-error' : '' }}">
                            <label for="site" class="col-md-4 control-label">Site</label>
                            <div class="col-md-6">
                                <input id="site" type="text" class="form-control" name="site" value="{{ old('site') }}" maxlength="180" required autofocus>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('usuarios_permitidos') ? ' has-error' : '' }}">
                            <label for="usuarios_permitidos" class="col-md-4 control-label">Usuário(s) Permitido(s)</label>
                            <div class="col-md-6">
                                <textarea id="usuarios_permitidos"  class="form-control" name="usuarios_permitidos" value="{{ old('usuarios_permitidos') }}"></textarea>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('permanente') ? ' has-error' : '' }}">
                            <label for="permanente" class="col-md-4 control-label">Permanente</label>
                                <input id="permanente" name="permanente"   type="checkbox" value="1">
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Cadastrar
                                </button>
                                <a href="{{URL::previous()}}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </form>

                    <div class="row">
                        <ul>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mensagem/destroy.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>EXCLUSÃO DE MENSAGENS</strong></div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('mensagem.remove', ['id'=> $dadosMensagem->id]) }}">
                         <input type="hidden" id="key" name="key" value="{{$dadosMensagem->id}}">
                        {{ csrf_field() }}
                        @if (\Session::has('success'))
                            <div class="alert alert-success">
                                <p>{{ \Session::get('success') }}</p>
                            </div><br />
                        @endif
                        <div class="form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
                            <label for="descricao" class="col-md-4 control-label">Descrição: </label>
                            <label for="descricao" class="control-label">{{ str_limit($dadosMensagem->descricao, $limit = 50, $end = '............')  }}</label>
                        </div>
                        <div class="form-group{{ $errors->has('site') ? ' has-error' : '' }}">
                            <label for="site" class="col-md-4 control-label">Site: </label>
                            <label for="site" class="control-label">{{ $dadosMensagem->site }}</label>
                        </div>
                         <div class="form-group{{ $errors->has('usuarios_permitidos') ? ' has-error' : '' }}">
                            <label for="usuarios_permitidos" class="col-md-4 control-label">Usuário(s) Permitido(s): </label>
                            <label for="descricao" class="control-label">{{ $dadosMensagem->usuarios_permitidos }}</label>
                        </div>
                        <div class="form-group{{ $errors->has('permanente') ? ' has-error' : '' }}">
                            <label for="permanente" class="col-md-4 control-label">Permanente: </label>
                            <label for="descricao" class="control-label">{{ ($dadosMensagem->permanente ? 'SIM' : 'NÃO') }}</label>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-danger">
                                    Excluir
                                </button>
                                <a href="{{URL::previous()}}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </form>

                    <div class="row">
                    <ul>
                    
                    </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mensagem/detailpageEdit.blade.php
@extends('layouts.app')

@section('content')
<h1>Atualização realizada com sucesso</h1>
<h2>{{ $detailpage->nome }}</h2>
<p>
    {{ $detailpage->descricao }}
</p>
<a href="/mensagem">Voltar</a>
@endsection

resources/views/mensagem/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>EDIÇÃO DAS MENSAGENS</strong></div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('mensagem.store') }}">
                         <input type="hidden" id="key" name="key" value="{{$dadosMensagem->id}}">
                        {{ csrf_field() }}
                        @if (\Session::has('success'))
                            <div class="alert alert-success">
                                <p>{{ \Session::get('success') }}</p>
                            </div><br />
                        @endif
                        <div class="form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
                            <label for="descricao" class="col-md-4 control-label">Mensagem</label>
                           
                            <div class="col-md-6">
                                <textarea id="descricao"  class="form-control" name="descricao"  required autofocus >{{ $dadosMensagem->descricao }}</textarea>
                                
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('site') ? ' has-error' : '' }}">
                            <label for="site" class="col-md-4 control-label">Site</label>
                            <div class="col-md-6">
                                <input id="site" type="text" class="form-control" name="site" value="{{ $dadosMensagem->site }}" required autofocus>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('usuarios_permitidos') ? ' has-error' : '' }}">
                            <label for="usuarios_permitidos" class="col-md-4 control-label">Usuário(s) Permitido(s)</label>
                            <div class="col-md-6">
                                <textarea id="usuarios_permitidos"  class="form-control" name="usuarios_permitidos">{{ $dadosMensagem->usuarios_permitidos }}</textarea>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('permanente') ? ' has-error' : '' }}">
                            <label for="permanente" class="col-md-4 control-label">Permanente</label>
                                <input id="permanente" name="permanente"   type="checkbox" {{ ($dadosMensagem->permanente ? 'checked' : '') }}>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Editar
                                </button>
                                <a href="{{URL::previous()}}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </form>

                    <div class="row">
                    <ul>
                    
                    </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mensagem/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <form class="form-horizontal" method="GET" action="{{ route('mensagem.create') }}">
                    <button type="submit" class="btn btn-success">
                        Nova Mensangem
                    </button>
                </form>
                <div class="panel-heading"><h3><strong>MENSAGENS CADASTRADAS</strong></h3>&nbsp; </div>
                <table class = "table table-striped table-responsive table-bordered table-hover" id = "dataTables-example">
                    <thead>
                    <th>MENSAGEM</th>
                    <th>CÓDIGO</th>
                    <th>CHAVE</th>
                    <th>SITE</th>    
                    <!--th>PERMANENTE</th-->
                    <th></th> 
                     
                    </thead>
                    <tbody>
                        @foreach($mensagensusuario as $item)
                        <tr class = "gradeC">
                            <td title="{{$item->descricao}}">{{str_limit($item->descricao, $limit = 80, $end = '............')}}</td>
                            <td title="Campo utilizado como parâmetro para geração do popup. Identifica o usuário que criou a mensagem.">{{$item->codigo}}</td>
                            <td title="Campo utilizado como parâmetro para geração do popup. Chave única que identifica o site para qual a mensagem cadastrada.">{{$item->chave}}</td>
                            <td><strong>{{$item->site}}</strong></td>
                            <!--td>{{ ($item->permanente ? 'SIM' : 'NÃO') }}</td-->
                            <td><a href="{{ route('mensagem.edit', ['id'=> $item->id]) }}" class="btn btn-danger">Editar</a></td>
                            <td><a href="{{ route('mensagem.destroy', ['id'=> $item->id]) }}" class="btn btn-warning">Excluir</a></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection